Add database
volkovask/java-filmorate pull request #12
Opened 2022-11-27 19:07 UTC by volkovask

2022-11-28 08:37 UTC, volkovask commented
Анастасия, привет.
Пока не могу понять, как их повторно залить.
Но файлы на месте их можно глянуть через Viewed/View file
![Empty_files](https://user-images.githubusercontent.com/102345034/204231235-e6f8af6f-f4fb-4bcb-a164-79e6e956f43f.png)

2022-11-29 07:23 UTC, AnastasiyaFomkina requested changes
Некоторые файлы сборки все еще остались пустыми, восстанови, пожалуйста

2022-11-29 07:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/utils/FilmStorageUtils.java
> +@Service
Лучше либо оставить класс-сервис, тогда его надо будет инжектить в те классы, где его используем и убрать всю статику или убрать `@Service` и оставить класс утильным, как он есть сейчас. Первый вариант более безопасный и поддерживаемый, второй простой :)

2022-11-29 07:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/utils/GenreStorageUtils.java
> +    private GenreStorageUtils() {
Конструктор нигде не используется, лучше удалить

2022-11-29 07:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/utils/MpaStorageUtils.java
> +    private MpaStorageUtils() {
Конструктор нигде не используется, лучше удалить

2022-11-29 07:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/utils/UserStorageUtils.java
> +    private UserStorageUtils() {
Конструктор нигде не используется, лучше удалить

2022-11-29 07:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/utils/UserStorageUtils.java
> +    public static User makeUser(ResultSet resultSet, int rowNum) throws SQLException {
Лишний параметр `int rowNum` лучше удалить

2022-11-29 07:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            PreparedStatement stm = connection.prepareStatement(
Лучше называть переменные осмысленно, сокращения и однобуквенные переменные делают код менее читаемым. 
Переименуй, пожалуйста, по всему проекту

2022-11-29 07:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDbStorage.java
> +        if (genres == null) {
Мы получим из базы либо пустой список, либо список с элементами, поэтому мы никогда не зайдем внутрь этого if. Лучше завязаться на какое-то другое условие

2022-11-29 07:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Genre> genres;
Не хватает модификатора доступа

2022-11-29 07:23 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/tests/UserDbStorageTest.java
> +public class UserDbStorageTest {
👍

2022-11-29 08:48 UTC, volkovask commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDbStorage.java
> +        if (genres == null) {
Убрал условие и обернул в Optional.

2022-11-29 08:48 UTC, volkovask commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Genre> genres;
Добавил модификатор доступа.

2022-11-29 08:48 UTC, volkovask commented on src/main/java/ru/yandex/practicum/filmorate/dao/utils/UserStorageUtils.java
> +    public static User makeUser(ResultSet resultSet, int rowNum) throws SQLException {
Без этого параметра не будет работать RowMapper.
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/RowMapper.html
Прошу его оставить.

2022-11-29 08:48 UTC, volkovask commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +
Исправил.

2022-11-29 08:54 UTC, volkovask commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            PreparedStatement stm = connection.prepareStatement(
Переименовал переменную в preparedStatement.

2022-11-29 09:02 UTC, volkovask commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    GenreController(GenreService genreService) {
В этом классе не стал использовать Lombok.
На будущее изучу, как использовать Lombok не только в моделях.

2022-11-29 09:28 UTC, volkovask commented on src/main/java/ru/yandex/practicum/filmorate/dao/utils/MpaStorageUtils.java
> +    private MpaStorageUtils() {
Удалил.

2022-11-29 09:28 UTC, volkovask commented on src/main/java/ru/yandex/practicum/filmorate/dao/utils/GenreStorageUtils.java
> +    private GenreStorageUtils() {
Удалил.

2022-11-29 09:40 UTC, volkovask commented on src/main/java/ru/yandex/practicum/filmorate/dao/utils/FilmStorageUtils.java
> +@Service
При втором варианте сломается матчинг жанров.
Анастасия, возможен вариант оставить, как есть?
Мне необходимо больше времени для того, чтобы более осознано изучить эту тему.
И как всегда дедлайн не дает расслабиться и времени. :)

2022-11-29 15:05 UTC, AnastasiyaFomkina commented on mvnw.cmd
> +
Смотри, можно попробовать вытащить изменения из initial commita, если в идее проект подключен к репозиторию, это очень легко сделать с помощью встроенных функций: 
Можно будет сравнить файлы или реветнуть их состояние
<img width="1744" alt="Снимок экрана 2022-11-29 в 18 01 29" src="https://user-images.githubusercontent.com/43168217/204565128-be0737bf-9168-4652-b651-85bbe14e6e31.png">

2022-11-29 15:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/utils/FilmStorageUtils.java
> +@Service
Ок

2022-11-29 15:18 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    GenreController(GenreService genreService) {
Хорошо

2022-11-29 15:26 UTC, AnastasiyaFomkina commented on mvnw.cmd
> +
Сначала нужно зайти в гит и выбрать все логи. В пункте 3 -  выбрать коммит из которого хотим восстановить изменения,  4 - файл, который поменялся. На нем нужно нажать правой кнопкой мыши
<img width="1779" alt="Снимок экрана 2022-11-29 в 18 22 11" src="https://user-images.githubusercontent.com/43168217/204569967-949178bd-ec2a-4eb1-8270-eca6461cfac2.png">

2022-11-29 15:28 UTC, AnastasiyaFomkina commented on mvnw.cmd
> +
<img width="515" alt="Снимок экрана 2022-11-29 в 18 26 50" src="https://user-images.githubusercontent.com/43168217/204571130-ae1f7c35-ed07-4dd8-bec0-06f2f0fed1de.png">
Сравнить старый файл с тем, что есть сейчас и перенести все изменения из старого в новый:
<img width="1493" alt="Снимок экрана 2022-11-29 в 18 27 04" src="https://user-images.githubusercontent.com/43168217/204571314-11acdd03-4459-4f4c-a69f-a6ecd476e464.png">

2022-11-30 08:53 UTC, AnastasiyaFomkina approved these changes

2022-12-01 17:23 UTC, merged